services:
  app:
    build:
      context: . 
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: "postgresql://postgres:root1234@db:5432/Task_Manager?schema=public"
      NODE_ENV: "production"
    depends_on:
      - db 
    volumes:
      - .:/app
      - /app/node_modules 
    stdin_open: true 
  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: Task_Manager
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
volumes:
  postgres_data: