services:
  app:
    build:
      context: . 
    image: task_manager:latest
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: "postgresql://postgres:root1234@host.docker.internal:5432/Task_Manager?schema=public"  # Usa host.docker.internal
      NODE_ENV: "production"
    depends_on:
      - db
    volumes:
      - /app/node_modules 
    stdin_open: true 
    command: /bin/sh -c "npx prisma migrate deploy && npm start"
  db:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: Task_Manager
    ports:
      - "5432:5432"
